name: static-news Update prod
run-name: ${{ github.actor }}
on:
  # schedule:
  #   - cron: '0 0 * * *'
  push
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - name: Set Git config
        run: |
          git config --local user.email "sbuggay@users.noreply.github.com"
          git config --local user.name "${{ env.CI_COMMIT_AUTHOR }}"
      - name: Merge master back to dev
        run: |
          git fetch --unshallow
          git checkout prod
          git pull
          git merge --no-ff master -m "Auto-merge master"
          git push
