name: static-news build
run-name: ${{ github.actor }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: echo "Using Node.js@${{matrix.node-version}}"
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - run: npm i
      - run: npm run build
      - run: echo "Complete"