name: static-news Merge master into prod
run-name: ${{ github.actor }}
on:
  schedule:
    - cron: '0 9 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@master
      - name: Merge master -> prod
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: prod
          github_token: ${{ secrets.GITHUB_TOKEN }}